# Generated by Django 4.2 on 2023-04-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='muber_of_seats',
            new_name='nuber_of_seats',
        ),
    ]
